<!-- ReimaginedOS - Copyright (C) ReimaginedOS and cr1mix | Licensed under the GNU General Public License v3.0 or later - see LICENSE.txt -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AssemblyName>ReimaginedOSTimer</AssemblyName>
    <Version>1.0.0</Version>
    <Company>cr1mix - ReimaginedOS</Company>
  </PropertyGroup>
</Project>
